### ISSUE TITLE
Installing error on windows 10 

### ISSUE THREAD

**Issue by giahung24** [rmit-ir/KrovetzStemmer#3]
Hi,
I have this error when trying to installing on windows 10 64bit:

>pip install krovetzstemmer
Collecting krovetzstemmer
  Using cached KrovetzStemmer-0.5.tar.gz
Building wheels for collected packages: krovetzstemmer
  Running setup.py bdist_wheel for krovetzstemmer: started
  Running setup.py bdist_wheel for krovetzstemmer: finished with status 'error'
  Complete output from command C:\ProgramData\Miniconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Jean\\AppData\\Local\\Temp\\pip-build-widgdg1m\\krovetzstemmer\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\Jean\AppData\Local\Temp\tmpsooe279ipip-wheel- --python-tag cp35:
  running bdist_wheel
  running build
  running build_ext
  building 'krovetzstemmer' extension
  creating build
  creating build\temp.win-amd64-3.5
  creating build\temp.win-amd64-3.5\Release
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\ProgramData\Miniconda3\include -IC:\ProgramData\Miniconda3\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\8.1\include\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\winrt" /EHsc /Tpkrovetzstemmer_module.cpp /Fobuild\temp.win-amd64-3.5\Release\krovetzstemmer_module.obj
  krovetzstemmer_module.cpp
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\hash_map(17): error C2338: <hash_map> is deprecated and will be REMOVED. Please use <unordered_map>. You can define _SILENCE_STDEXT_HASH_DEPRECATION_WARNINGS to acknowledge that you have received this warning.
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2
  Failed building wheel for krovetzstemmer
  Running setup.py clean for krovetzstemmer
Failed to build krovetzstemmer
Installing collected packages: krovetzstemmer
  Running setup.py install for krovetzstemmer: started
    Running setup.py install for krovetzstemmer: finished with status 'error'
    Complete output from command C:\ProgramData\Miniconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Jean\\AppData\\Local\\Temp\\pip-build-widgdg1m\\krovetzstemmer\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Jean\AppData\Local\Temp\pip-ubotddeo-record\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    building 'krovetzstemmer' extension
    creating build
    creating build\temp.win-amd64-3.5
    creating build\temp.win-amd64-3.5\Release
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\ProgramData\Miniconda3\include -IC:\ProgramData\Miniconda3\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\8.1\include\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\winrt" /EHsc /Tpkrovetzstemmer_module.cpp /Fobuild\temp.win-amd64-3.5\Release\krovetzstemmer_module.obj
    krovetzstemmer_module.cpp
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\hash_map(17): error C2338: <hash_map> is deprecated and will be REMOVED. Please use <unordered_map>. You can define _SILENCE_STDEXT_HASH_DEPRECATION_WARNINGS to acknowledge that you have received this warning.
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2
Command "C:\ProgramData\Miniconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Jean\\AppData\\Local\\Temp\\pip-build-widgdg1m\\krovetzstemmer\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Jean\AppData\Local\Temp\pip-ubotddeo-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\Jean\AppData\Local\Temp\pip-build-widgdg1m\krovetzstemmer\

Do you have any idea? 
Thank you.

**Comment by rueycheng** [comment]
Hi,

I think this is where it got you:

> C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\hash_map(17): error C2338: <hash_map> is deprecated and will be REMOVED. Please use <unordered_map>. You can define _SILENCE_STDEXT_HASH_DEPRECATION_WARNINGS to acknowledge that you have received this warning.

Can I count on you to try this one out?
1. Clone this repo and cd into it
2. Change Line 19 in `KrovetzStemmer.hpp` into: `#if defined(_WIN32) || defined(_WIN64)`
3. Do `pip install .`

See how that works for you.

**Comment by giahung24** [comment]
It works.

Thank you! 💯

**Comment by rueycheng** [comment]
Awesome.  I've put in a fix and this will be made available shortly on PyPI.

Cheers.

**Comment by Sreeja-coder** [comment]
i am trying to install krovetz stemmer but it fails with the following error
command used : >pip install -i https://test.pypi.org/simple/ krovetz



Microsoft Windows [Version 10.0.18363.1139]
(c) 2019 Microsoft Corporation. All rights reserved.

(IR_project) C:\Sreeja\Python_Projects\IR_project>
(IR_project) C:\Sreeja\Python_Projects\IR_project>
(IR_project) C:\Sreeja\Python_Projects\IR_project>pip install -i https://test.pypi.org/simple/ krovetz
Looking in indexes: https://test.pypi.org/simple/
Collecting krovetz
  Downloading https://test-files.pythonhosted.org/packages/db/67/47724e97f563121bd14d946bea739d664979c8286c1b90b77b81e1e0e59e/krovetz-1.0.0.tar.gz (137 kB)
     |████████████████████████████████| 137 kB 1.1 MB/s
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\sreej\.virtualenvs\IR_project-Pn43L36S\Scripts\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\sreej\\AppData
\\Local\\Temp\\pip-install-a6qpm4y6\\krovetz\\setup.py'"'"'; __file__='"'"'C:\\Users\\sreej\\AppData\\Local\\Temp\\pip-install-a6qpm4y6\\krovetz\\setup.py'"'"';f=get
attr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info
--egg-base 'C:\Users\sreej\AppData\Local\Temp\pip-pip-egg-info-kim_j3mp'
         cwd: C:\Users\sreej\AppData\Local\Temp\pip-install-a6qpm4y6\krovetz\
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\sreej\AppData\Local\Temp\pip-install-a6qpm4y6\krovetz\setup.py", line 77, in <module>
        version = version(),
      File "C:\Users\sreej\AppData\Local\Temp\pip-install-a6qpm4y6\krovetz\setup.py", line 21, in version
        stdout = subprocess.PIPE, universal_newlines = True)
      File "c:\users\sreej\appdata\local\programs\python\python36\lib\subprocess.py", line 707, in __init__
        restore_signals, start_new_session)
      File "c:\users\sreej\appdata\local\programs\python\python36\lib\subprocess.py", line 990, in _execute_child
        startupinfo)
    FileNotFoundError: [WinError 2] The system cannot find the file specified
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by rueycheng** [comment]
@Sreeja-coder I think your question should be directed to this repo instead? https://github.com/ptorrestr/py_krovetz

**Comment by rohan2810** [comment]
Having a similar issue on Linux based system. I even tried cloning this repo and pip install .
Still the same issue.
```
Collecting krovetzstemmer
  Using cached KrovetzStemmer-0.8.tar.gz (112 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: krovetzstemmer
  Building wheel for krovetzstemmer (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [16 lines of output]
      In file included from /usr/include/string.h:535,
                       from /usr/include/c++/11/cstring:42,
                       from KrovetzStemmer.hpp:18,
                       from KrovetzStemmer.cpp:39:
      In function ‘char* strncpy(char*, const char*, size_t)’,
          inlined from ‘int stem::KrovetzStemmer::kstem_stem_tobuffer(char*, char*)’ at KrovetzStemmer.cpp:1022:5:
      /usr/include/x86_64-linux-gnu/bits/string_fortified.h:95:34: warning: ‘char* __builtin_strncpy(char*, const char*, long unsigned int)’ specified bound 12 equals destination size [-Wstringop-truncation]
         95 |   return __builtin___strncpy_chk (__dest, __src, __len,
            |          ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~
         96 |                                   __glibc_objsize (__dest));
            |                                   ~~~~~~~~~~~~~~~~~~~~~~~~~
      krovetzstemmer_module.cpp:1:10: fatal error: Python.h: No such file or directory
          1 | #include <Python.h>
            |          ^~~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/x86_64-linux-gnu-g++' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for krovetzstemmer
  Running setup.py clean for krovetzstemmer
Failed to build krovetzstemmer
ERROR: Failed to build installable wheels for some pyproject.toml based projects (krovetzstemmer)
```
